# Generated by Django 5.2.3 on 2025-06-11 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0002_terraindigenareferencia_alter_alteracoes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terraindigenareferencia',
            options={'ordering': ['nome'], 'verbose_name': 'Terra Indígena (Referência)', 'verbose_name_plural': 'Terras Indígenas (Referência)'},
        ),
        migrations.RemoveField(
            model_name='terraindigenareferencia',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='terraindigenareferencia',
            name='populacao',
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='coordenacao_regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='data_declarada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='data_delimitada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='data_em_estudo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='data_homologada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='data_regularizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='fase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='terraindigenareferencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='terraindigenareferencia',
            name='area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terraindigenareferencia',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='terraindigenareferencia',
            name='etnia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='terraindigenareferencia',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
