# Generated by Django 5.2.3 on 2025-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0007_alter_lancamentotipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='origem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
