# Generated by Django 5.2.3 on 2025-07-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0024_alter_tis_etnia_alter_tis_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorios',
            options={'ordering': ['tipo', 'estado', 'cidade', 'nome'], 'verbose_name': 'Cartório', 'verbose_name_plural': 'Cartórios'},
        ),
        migrations.AddField(
            model_name='cartorios',
            name='tipo',
            field=models.CharField(choices=[('CRI', 'Cartório de Registro de Imóveis'), ('OUTRO', 'Outro')], default='CRI', max_length=10, verbose_name='Tipo de Cartório'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cri_atual',
            field=models.ForeignKey(blank=True, help_text='Cartório de Registro de Imóveis atual do documento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cri_atual', to='dominial.cartorios', verbose_name='CRI Atual'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cri_origem',
            field=models.ForeignKey(blank=True, help_text='Cartório de Registro de Imóveis da origem (quando criado automaticamente)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cri_origem', to='dominial.cartorios', verbose_name='CRI da Origem'),
        ),
    ]
