# Generated by Django 5.2.3 on 2025-07-10 13:19
#
# Tornada no-op: a migração 0025 já adiciona `cri_atual` e `cri_origem` a
# Documento. Ambientes que aplicaram esta migração antes da correção
# permanecem inalterados (o Django só verifica o nome como aplicado); bancos
# novos deixam de falhar por tentar adicionar as mesmas colunas duas vezes.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0025_alter_cartorios_options_cartorios_tipo_and_more'),
    ]

    operations = []
