# Generated by Django 5.2.3 on 2025-07-10 13:19
# NOTE: This migration was originally adding cri_atual and cri_origem fields,
# but those were already added in migration 0025. This migration is now a no-op
# to maintain the migration chain without causing "duplicate column" errors.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0025_alter_cartorios_options_cartorios_tipo_and_more'),
    ]

    operations = [
        # No operations - fields already added in migration 0025
    ]
