# Generated by Django 5.2.3 on 2025-07-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0025_alter_cartorios_options_cartorios_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='cartorio_transacao',
            field=models.ForeignKey(blank=True, help_text='Cartório onde foi registrada a transmissão', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartorio_transacao_lancamento', to='dominial.cartorios'),
        ),
    ]
