# Generated by Django 5.2.3 on 2025-07-10 15:39

from django.db import migrations


def sync_cartorio_transmissao_data(apps, schema_editor):
    """
    Sincroniza dados do campo cartorio_transacao para cartorio_transmissao
    """
    Lancamento = apps.get_model('dominial', 'Lancamento')
    
    # Copiar dados do campo antigo para o novo
    for lancamento in Lancamento.objects.all():
        if (lancamento.cartorio_transmissao is None and 
            lancamento.cartorio_transacao is not None):
            lancamento.cartorio_transmissao = lancamento.cartorio_transacao
            lancamento.save()


def reverse_sync_cartorio_transmissao_data(apps, schema_editor):
    """
    Reverte a sincronização (não é necessário, mas mantém a migration reversível)
    """
    Lancamento = apps.get_model('dominial', 'Lancamento')
    
    # Limpar o campo novo (opcional, só se quiser reverter)
    for lancamento in Lancamento.objects.all():
        if lancamento.cartorio_transmissao is not None:
            lancamento.cartorio_transmissao = None
            lancamento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0028_add_cartorio_transmissao'),
    ]

    operations = [
        migrations.RunPython(
            sync_cartorio_transmissao_data,
            reverse_sync_cartorio_transmissao_data
        ),
    ]
