# Generated by Django 5.2.3 on 2025-09-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0040_add_arquivado_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FimCadeia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do fim de cadeia (ex: Estado da Bahia, INCRA)', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('destacamento_publico', 'Destacamento Público'), ('outra', 'Outra'), ('sem_origem', 'Sem Origem')], default='destacamento_publico', max_length=50)),
                ('classificacao', models.CharField(choices=[('origem_lidima', 'Origem Lídima'), ('sem_origem', 'Sem Origem'), ('inconclusa', 'Situação Inconclusa')], default='origem_lidima', max_length=50)),
                ('sigla', models.CharField(blank=True, help_text='Sigla do órgão (ex: INCRA, SPU)', max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do fim de cadeia', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se o fim de cadeia está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fim de Cadeia',
                'verbose_name_plural': 'Fins de Cadeia',
                'ordering': ['nome'],
            },
        ),
    ]
