# Generated by Django 5.2.3 on 2025-01-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0041_fimcadeia'),
    ]

    operations = [
        # Add the imovel_destino field
        migrations.AddField(
            model_name='documentoimportado',
            name='imovel_destino',
            field=models.ForeignKey(
                blank=True,
                help_text='Imóvel para onde o documento foi importado',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documentos_importados',
                to='dominial.imovel',
                verbose_name='Imóvel de Destino'
            ),
        ),
        # Add related_name to imovel_origem
        migrations.AlterField(
            model_name='documentoimportado',
            name='imovel_origem',
            field=models.ForeignKey(
                help_text='Imóvel de onde o documento foi importado',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documentos_exportados',
                to='dominial.imovel',
                verbose_name='Imóvel de Origem'
            ),
        ),
        # Add index for imovel_destino
        migrations.AddIndex(
            model_name='documentoimportado',
            index=models.Index(fields=['imovel_destino'], name='dominial_do_imovel__dest_idx'),
        ),
    ]
