# Generated by Django 5.2.3 on 2025-01-19

from django.db import migrations


def populate_imovel_destino(apps, schema_editor):
    """
    Populate imovel_destino for existing DocumentoImportado records.

    For old imports where documents were moved to the destination,
    we use the document's current imóvel as the destination.
    """
    DocumentoImportado = apps.get_model('dominial', 'DocumentoImportado')

    # Get all records with NULL imovel_destino
    records_to_update = DocumentoImportado.objects.filter(imovel_destino__isnull=True)

    for record in records_to_update:
        # The document's current imóvel is the destination
        # (since old imports moved the document there)
        record.imovel_destino = record.documento.imovel
        record.save(update_fields=['imovel_destino'])


def reverse_populate(apps, schema_editor):
    """
    Reverse migration - set imovel_destino back to NULL.
    """
    DocumentoImportado = apps.get_model('dominial', 'DocumentoImportado')
    DocumentoImportado.objects.all().update(imovel_destino=None)


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0042_add_imovel_destino_to_documentoimportado'),
    ]

    operations = [
        migrations.RunPython(populate_imovel_destino, reverse_populate),
    ]
