# Generated by Django 5.2.3 on 2026-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0046_lancamento_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentoorigem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
