# Generated by Django 5.2.3 on 2026-07-31 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0050_remove_fimcadeia_classificacao_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_digitais/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamanho_bytes', models.PositiveIntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_digitais', to='dominial.documento')),
                ('upload_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Digital',
                'verbose_name_plural': 'Documentos Digitais',
                'ordering': ['-data_upload'],
            },
        ),
    ]
