# Generated by Django 5.2.3 on 2026-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0051_documentodigital'),
    ]

    operations = [
        migrations.AddField(
            model_name='origemfimcadeia',
            name='info_adicional_fim_cadeia',
            field=models.CharField(blank=True, help_text='Informação adicional do destacamento (ex: secretaria que concedeu o título)', max_length=255, null=True),
        ),
    ]
