# Generated by Django 6.0.7 on 2026-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0054_normaliza_fim_cadeia_destacamento_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_presumida',
            field=models.BooleanField(db_index=True, default=False, help_text='True quando a data não é um dado jurídico real, mas a data de cadastro no sistema.'),
        ),
    ]
