# Generated by Django 6.0.7 on 2026-08-06 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0056_normaliza_none_textual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True, verbose_name='Data da atribuição')),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_atribuidos', to='dominial.imovel', verbose_name='Imóvel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atribuição de Imóvel',
                'verbose_name_plural': 'Atribuições de Imóveis',
                'ordering': ['user__username', 'imovel__matricula'],
                'unique_together': {('user', 'imovel')},
            },
        ),
    ]
