# Generated by Django 6.0.7 on 2026-08-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dominial', '0058_atribui_imoveis_existentes_superusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('perfil', 'Perfil'), ('equipe', 'Equipe')], max_length=10)),
                ('protegido', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_grupo_feitas', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tis_atribuidas', to='auth.group', verbose_name='Equipe')),
                ('tis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_ti', to='dominial.tis')),
            ],
            options={
                'indexes': [models.Index(fields=['tis'], name='dom_groupti_tis_idx')],
                'unique_together': {('group', 'tis')},
            },
        ),
        migrations.CreateModel(
            name='UserTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_ti_feitas', to=settings.AUTH_USER_MODEL)),
                ('tis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_ti', to='dominial.tis', verbose_name='Terra Indígena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tis_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atribuição de TI',
                'verbose_name_plural': 'Atribuições de TI',
                'ordering': ['user__username', 'tis__nome'],
                'indexes': [models.Index(fields=['tis'], name='dom_userti_tis_idx')],
                'unique_together': {('user', 'tis')},
            },
        ),
    ]
