# Generated by Django 6.0.7 on 2026-08-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dominial', '0060_seed_perfis'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoacesso',
            name='acesso_todas_tis',
            field=models.BooleanField(db_index=True, default=False, help_text='Equipe "global": todo membro passa a ver todas as TIs — as atuais e as cadastradas no futuro — e todos os imóveis dessas TIs. É uma propriedade calculada dinamicamente pelo manager de segregação, não gera linhas em GroupTI e não precisa de sincronização quando uma TI nova é criada. Só é válido para equipes (tipo=EQUIPE); perfis nunca podem ativá-lo.', verbose_name='Acesso a todas as TIs'),
        ),
        migrations.AddConstraint(
            model_name='grupoacesso',
            constraint=models.CheckConstraint(condition=models.Q(('acesso_todas_tis', False), ('tipo', 'equipe'), _connector='OR'), name='grupoacesso_global_so_equipe', violation_error_message='Acesso a todas as TIs só pode ser ativado para equipes, não para perfis.'),
        ),
    ]
