version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: cadeia_dominial_db
    environment:
      POSTGRES_DB: ${DB_NAME:-cadeia_dominial}
      POSTGRES_USER: ${DB_USER:-cadeia_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sua_senha_segura_aqui}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - cadeia_network
    restart: unless-stopped

  # Aplicação Django
  web:
    build: .
    container_name: cadeia_dominial_web
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME:-cadeia_dominial}
      - DB_USER=${DB_USER:-cadeia_user}
      - DB_PASSWORD=${DB_PASSWORD:-sua_senha_segura_aqui}
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DJANGO_SETTINGS_MODULE=cadeia_dominial.settings_prod
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@cadeiadominial.com.br}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
    networks:
      - cadeia_network
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 cadeia_dominial.wsgi:application"

  # Nginx com SSL
  nginx:
    image: nginx:alpine
    container_name: cadeia_dominial_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./staticfiles:/var/www/static:ro
      - ./media:/var/www/media:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - web
    networks:
      - cadeia_network
    restart: unless-stopped

  # Certbot para SSL automático
  certbot:
    image: certbot/certbot
    container_name: cadeia_dominial_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME}
    networks:
      - cadeia_network

volumes:
  postgres_data:

networks:
  cadeia_network:
    driver: bridge 