--
-- PostgreSQL database dump
--

\restrict lfMmYSJ8ocw5F0q6xopoJejxA2i0Xt8FKEsbwKGlc4um26gG06SmyAO35v3t6Bc

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: dominial_alteracoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_alteracoes (
    id integer NOT NULL,
    livro character varying(50),
    folha character varying(50),
    data_alteracao date,
    titulo character varying(255),
    livro_origem character varying(50),
    folha_origem character varying(50),
    data_origem date,
    valor_transacao numeric(10,2),
    area numeric(12,4),
    observacoes text,
    data_cadastro date NOT NULL,
    tipo_alteracao_id_id integer NOT NULL,
    averbacao_tipo_id integer,
    cartorio_id bigint NOT NULL,
    cartorio_origem_id bigint NOT NULL,
    imovel_id_id integer NOT NULL,
    adquirente_id integer,
    transmitente_id integer,
    registro_tipo_id integer
);


--
-- Name: dominial_alteracoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_alteracoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_alteracoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_alteracoestipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_alteracoestipo (
    id integer NOT NULL,
    tipo character varying(50) NOT NULL
);


--
-- Name: dominial_alteracoestipo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_alteracoestipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_alteracoestipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_averbacoestipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_averbacoestipo (
    id integer NOT NULL,
    tipo character varying(100) NOT NULL
);


--
-- Name: dominial_averbacoestipo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_averbacoestipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_averbacoestipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_cartorios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_cartorios (
    id bigint NOT NULL,
    nome character varying(200) NOT NULL,
    cns character varying(20) NOT NULL,
    endereco character varying(200),
    telefone character varying(20),
    email character varying(254),
    cidade character varying(100),
    estado character varying(2),
    tipo character varying(10) NOT NULL
);


--
-- Name: dominial_cartorios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_cartorios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_cartorios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_documento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_documento (
    id integer NOT NULL,
    numero character varying(50) NOT NULL,
    data date NOT NULL,
    livro character varying(50) NOT NULL,
    folha character varying(50) NOT NULL,
    observacoes text,
    data_cadastro date NOT NULL,
    cartorio_id bigint NOT NULL,
    imovel_id integer NOT NULL,
    tipo_id integer NOT NULL,
    origem text,
    nivel_manual integer,
    cri_atual_id bigint,
    cri_origem_id bigint,
    classificacao_fim_cadeia character varying(50),
    sigla_patrimonio_publico character varying(50)
);


--
-- Name: dominial_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_documento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_documentoimportado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_documentoimportado (
    id bigint NOT NULL,
    data_importacao timestamp with time zone NOT NULL,
    documento_id integer NOT NULL,
    imovel_origem_id integer NOT NULL,
    importado_por_id integer
);


--
-- Name: dominial_documentoimportado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_documentoimportado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_documentoimportado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_documentotipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_documentotipo (
    id integer NOT NULL,
    tipo character varying(50) NOT NULL
);


--
-- Name: dominial_documentotipo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_documentotipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_documentotipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_fimcadeia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_fimcadeia (
    id integer NOT NULL,
    nome character varying(100) NOT NULL,
    tipo character varying(50) NOT NULL,
    classificacao character varying(50) NOT NULL,
    sigla character varying(50),
    descricao text,
    ativo boolean NOT NULL,
    data_criacao timestamp with time zone NOT NULL,
    data_atualizacao timestamp with time zone NOT NULL
);


--
-- Name: dominial_fimcadeia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_fimcadeia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_fimcadeia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_imovel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_imovel (
    id integer NOT NULL,
    nome character varying(100) NOT NULL,
    matricula character varying(50) NOT NULL,
    observacoes text,
    data_cadastro date NOT NULL,
    cartorio_id bigint,
    proprietario_id integer NOT NULL,
    terra_indigena_id_id integer NOT NULL,
    tipo_documento_principal character varying(20) NOT NULL,
    arquivado boolean NOT NULL
);


--
-- Name: dominial_imovel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_imovel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_imovel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_importacaocartorios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_importacaocartorios (
    id bigint NOT NULL,
    estado character varying(2) NOT NULL,
    data_inicio timestamp with time zone NOT NULL,
    data_fim timestamp with time zone,
    total_cartorios integer NOT NULL,
    status character varying(20) NOT NULL,
    erro text
);


--
-- Name: dominial_importacaocartorios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_importacaocartorios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_importacaocartorios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_lancamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_lancamento (
    id integer NOT NULL,
    data date NOT NULL,
    valor_transacao numeric(10,2),
    area numeric(12,4),
    detalhes text,
    observacoes text,
    data_cadastro date NOT NULL,
    adquirente_id integer,
    documento_id integer NOT NULL,
    transmitente_id integer,
    tipo_id integer NOT NULL,
    cartorio_origem_id bigint,
    data_origem date,
    descricao text,
    documento_origem_id integer,
    eh_inicio_matricula boolean NOT NULL,
    folha_origem character varying(50),
    forma character varying(100),
    livro_origem character varying(50),
    titulo character varying(255),
    origem character varying(255),
    numero_lancamento character varying(50),
    cartorio_transacao_id bigint,
    data_transacao date,
    folha_transacao character varying(50),
    livro_transacao character varying(50),
    cartorio_transmissao_id bigint
);


--
-- Name: dominial_lancamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_lancamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_lancamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_lancamentopessoa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_lancamentopessoa (
    id bigint NOT NULL,
    tipo character varying(20) NOT NULL,
    nome_digitado character varying(255),
    lancamento_id integer NOT NULL,
    pessoa_id integer NOT NULL
);


--
-- Name: dominial_lancamentopessoa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_lancamentopessoa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_lancamentopessoa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_lancamentotipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_lancamentotipo (
    id integer NOT NULL,
    tipo character varying(50) NOT NULL,
    requer_detalhes boolean NOT NULL,
    requer_transmissao boolean NOT NULL,
    requer_cartorio_origem boolean NOT NULL,
    requer_data_origem boolean NOT NULL,
    requer_descricao boolean NOT NULL,
    requer_folha_origem boolean NOT NULL,
    requer_forma boolean NOT NULL,
    requer_livro_origem boolean NOT NULL,
    requer_observacao boolean NOT NULL,
    requer_titulo boolean NOT NULL
);


--
-- Name: dominial_lancamentotipo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_lancamentotipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_lancamentotipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_origemfimcadeia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_origemfimcadeia (
    id bigint NOT NULL,
    indice_origem integer NOT NULL,
    fim_cadeia boolean NOT NULL,
    tipo_fim_cadeia character varying(50),
    especificacao_fim_cadeia text,
    classificacao_fim_cadeia character varying(50),
    lancamento_id integer NOT NULL
);


--
-- Name: dominial_origemfimcadeia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_origemfimcadeia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_origemfimcadeia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_pessoas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_pessoas (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    cpf character varying(11),
    rg character varying(20),
    data_nascimento date,
    email character varying(254),
    telefone character varying(15)
);


--
-- Name: dominial_pessoas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_pessoas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_pessoas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_registrotipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_registrotipo (
    id integer NOT NULL,
    tipo character varying(100) NOT NULL
);


--
-- Name: dominial_registrotipo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_registrotipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_registrotipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_terraindigenareferencia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_terraindigenareferencia (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    nome character varying(255) NOT NULL,
    etnia character varying(255),
    estado character varying(100),
    municipio character varying(255),
    area_ha double precision,
    fase character varying(100),
    modalidade character varying(100),
    coordenacao_regional character varying(100),
    data_regularizada date,
    data_homologada date,
    data_declarada date,
    data_delimitada date,
    data_em_estudo date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: dominial_terraindigenareferencia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_terraindigenareferencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_terraindigenareferencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_tis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_tis (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    codigo character varying(50) NOT NULL,
    etnia character varying(255) NOT NULL,
    data_cadastro date NOT NULL,
    terra_referencia_id bigint,
    area numeric(12,2),
    estado character varying(100)
);


--
-- Name: dominial_tis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_tis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_tis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dominial_tis_imovel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dominial_tis_imovel (
    id bigint NOT NULL,
    imovel_id integer NOT NULL,
    tis_codigo_id integer NOT NULL
);


--
-- Name: dominial_tis_imovel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dominial_tis_imovel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dominial_tis_imovel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: dominial_alteracoes dominial_alteracoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_pkey PRIMARY KEY (id);


--
-- Name: dominial_alteracoestipo dominial_alteracoestipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoestipo
    ADD CONSTRAINT dominial_alteracoestipo_pkey PRIMARY KEY (id);


--
-- Name: dominial_averbacoestipo dominial_averbacoestipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_averbacoestipo
    ADD CONSTRAINT dominial_averbacoestipo_pkey PRIMARY KEY (id);


--
-- Name: dominial_cartorios dominial_cartorios_cns_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_cartorios
    ADD CONSTRAINT dominial_cartorios_cns_key UNIQUE (cns);


--
-- Name: dominial_cartorios dominial_cartorios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_cartorios
    ADD CONSTRAINT dominial_cartorios_pkey PRIMARY KEY (id);


--
-- Name: dominial_documento dominial_documento_numero_cartorio_id_2bb43be4_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_numero_cartorio_id_2bb43be4_uniq UNIQUE (numero, cartorio_id);


--
-- Name: dominial_documento dominial_documento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_pkey PRIMARY KEY (id);


--
-- Name: dominial_documentoimportado dominial_documentoimport_documento_id_imovel_orig_4eecd1d3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documentoimportado
    ADD CONSTRAINT dominial_documentoimport_documento_id_imovel_orig_4eecd1d3_uniq UNIQUE (documento_id, imovel_origem_id);


--
-- Name: dominial_documentoimportado dominial_documentoimportado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documentoimportado
    ADD CONSTRAINT dominial_documentoimportado_pkey PRIMARY KEY (id);


--
-- Name: dominial_documentotipo dominial_documentotipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documentotipo
    ADD CONSTRAINT dominial_documentotipo_pkey PRIMARY KEY (id);


--
-- Name: dominial_fimcadeia dominial_fimcadeia_nome_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_fimcadeia
    ADD CONSTRAINT dominial_fimcadeia_nome_key UNIQUE (nome);


--
-- Name: dominial_fimcadeia dominial_fimcadeia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_fimcadeia
    ADD CONSTRAINT dominial_fimcadeia_pkey PRIMARY KEY (id);


--
-- Name: dominial_imovel dominial_imovel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_imovel
    ADD CONSTRAINT dominial_imovel_pkey PRIMARY KEY (id);


--
-- Name: dominial_importacaocartorios dominial_importacaocartorios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_importacaocartorios
    ADD CONSTRAINT dominial_importacaocartorios_pkey PRIMARY KEY (id);


--
-- Name: dominial_lancamento dominial_lancamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_pkey PRIMARY KEY (id);


--
-- Name: dominial_lancamentopessoa dominial_lancamentopesso_lancamento_id_pessoa_id__496997b1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamentopessoa
    ADD CONSTRAINT dominial_lancamentopesso_lancamento_id_pessoa_id__496997b1_uniq UNIQUE (lancamento_id, pessoa_id, tipo);


--
-- Name: dominial_lancamentopessoa dominial_lancamentopessoa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamentopessoa
    ADD CONSTRAINT dominial_lancamentopessoa_pkey PRIMARY KEY (id);


--
-- Name: dominial_lancamentotipo dominial_lancamentotipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamentotipo
    ADD CONSTRAINT dominial_lancamentotipo_pkey PRIMARY KEY (id);


--
-- Name: dominial_origemfimcadeia dominial_origemfimcadeia_lancamento_id_indice_ori_97df39ae_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_origemfimcadeia
    ADD CONSTRAINT dominial_origemfimcadeia_lancamento_id_indice_ori_97df39ae_uniq UNIQUE (lancamento_id, indice_origem);


--
-- Name: dominial_origemfimcadeia dominial_origemfimcadeia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_origemfimcadeia
    ADD CONSTRAINT dominial_origemfimcadeia_pkey PRIMARY KEY (id);


--
-- Name: dominial_pessoas dominial_pessoas_cpf_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_pessoas
    ADD CONSTRAINT dominial_pessoas_cpf_key UNIQUE (cpf);


--
-- Name: dominial_pessoas dominial_pessoas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_pessoas
    ADD CONSTRAINT dominial_pessoas_pkey PRIMARY KEY (id);


--
-- Name: dominial_registrotipo dominial_registrotipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_registrotipo
    ADD CONSTRAINT dominial_registrotipo_pkey PRIMARY KEY (id);


--
-- Name: dominial_terraindigenareferencia dominial_terraindigenareferencia_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_terraindigenareferencia
    ADD CONSTRAINT dominial_terraindigenareferencia_codigo_key UNIQUE (codigo);


--
-- Name: dominial_terraindigenareferencia dominial_terraindigenareferencia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_terraindigenareferencia
    ADD CONSTRAINT dominial_terraindigenareferencia_pkey PRIMARY KEY (id);


--
-- Name: dominial_tis dominial_tis_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_tis
    ADD CONSTRAINT dominial_tis_codigo_key UNIQUE (codigo);


--
-- Name: dominial_tis_imovel dominial_tis_imovel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_tis_imovel
    ADD CONSTRAINT dominial_tis_imovel_pkey PRIMARY KEY (id);


--
-- Name: dominial_tis dominial_tis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_tis
    ADD CONSTRAINT dominial_tis_pkey PRIMARY KEY (id);


--
-- Name: dominial_imovel unique_matricula_por_cartorio; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_imovel
    ADD CONSTRAINT unique_matricula_por_cartorio UNIQUE (matricula, cartorio_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: dom_imovel_mat_cart_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dom_imovel_mat_cart_idx ON public.dominial_imovel USING btree (matricula, cartorio_id);


--
-- Name: dominial_alteracoes_adquirente_id_471a14a6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_adquirente_id_471a14a6 ON public.dominial_alteracoes USING btree (adquirente_id);


--
-- Name: dominial_alteracoes_averbacao_tipo_id_5df8eda8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_averbacao_tipo_id_5df8eda8 ON public.dominial_alteracoes USING btree (averbacao_tipo_id);


--
-- Name: dominial_alteracoes_cartorio_id_4225ad19; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_cartorio_id_4225ad19 ON public.dominial_alteracoes USING btree (cartorio_id);


--
-- Name: dominial_alteracoes_cartorio_origem_id_5c17b152; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_cartorio_origem_id_5c17b152 ON public.dominial_alteracoes USING btree (cartorio_origem_id);


--
-- Name: dominial_alteracoes_imovel_id_id_1a0ed79f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_imovel_id_id_1a0ed79f ON public.dominial_alteracoes USING btree (imovel_id_id);


--
-- Name: dominial_alteracoes_registro_tipo_id_09566af2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_registro_tipo_id_09566af2 ON public.dominial_alteracoes USING btree (registro_tipo_id);


--
-- Name: dominial_alteracoes_tipo_alteracao_id_id_0e059b13; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_tipo_alteracao_id_id_0e059b13 ON public.dominial_alteracoes USING btree (tipo_alteracao_id_id);


--
-- Name: dominial_alteracoes_transmitente_id_fd432374; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_alteracoes_transmitente_id_fd432374 ON public.dominial_alteracoes USING btree (transmitente_id);


--
-- Name: dominial_cartorios_cns_9bce347b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_cartorios_cns_9bce347b_like ON public.dominial_cartorios USING btree (cns varchar_pattern_ops);


--
-- Name: dominial_do_data_im_d37bf6_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_do_data_im_d37bf6_idx ON public.dominial_documentoimportado USING btree (data_importacao);


--
-- Name: dominial_do_documen_1fd8c4_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_do_documen_1fd8c4_idx ON public.dominial_documentoimportado USING btree (documento_id);


--
-- Name: dominial_do_imovel__658f12_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_do_imovel__658f12_idx ON public.dominial_documentoimportado USING btree (imovel_origem_id);


--
-- Name: dominial_do_importa_5dd212_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_do_importa_5dd212_idx ON public.dominial_documentoimportado USING btree (importado_por_id);


--
-- Name: dominial_documento_cartorio_id_a2f03235; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documento_cartorio_id_a2f03235 ON public.dominial_documento USING btree (cartorio_id);


--
-- Name: dominial_documento_cri_atual_id_d49d3fd5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documento_cri_atual_id_d49d3fd5 ON public.dominial_documento USING btree (cri_atual_id);


--
-- Name: dominial_documento_cri_origem_id_b95f93a9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documento_cri_origem_id_b95f93a9 ON public.dominial_documento USING btree (cri_origem_id);


--
-- Name: dominial_documento_imovel_id_a07f1631; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documento_imovel_id_a07f1631 ON public.dominial_documento USING btree (imovel_id);


--
-- Name: dominial_documento_tipo_id_65eb9188; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documento_tipo_id_65eb9188 ON public.dominial_documento USING btree (tipo_id);


--
-- Name: dominial_documentoimportado_documento_id_1dcef329; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documentoimportado_documento_id_1dcef329 ON public.dominial_documentoimportado USING btree (documento_id);


--
-- Name: dominial_documentoimportado_imovel_origem_id_ee4df2a9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documentoimportado_imovel_origem_id_ee4df2a9 ON public.dominial_documentoimportado USING btree (imovel_origem_id);


--
-- Name: dominial_documentoimportado_importado_por_id_f35b7a5c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_documentoimportado_importado_por_id_f35b7a5c ON public.dominial_documentoimportado USING btree (importado_por_id);


--
-- Name: dominial_fimcadeia_nome_e809508f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_fimcadeia_nome_e809508f_like ON public.dominial_fimcadeia USING btree (nome varchar_pattern_ops);


--
-- Name: dominial_imovel_cartorio_id_9936b98f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_imovel_cartorio_id_9936b98f ON public.dominial_imovel USING btree (cartorio_id);


--
-- Name: dominial_imovel_proprietario_id_f91e2468; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_imovel_proprietario_id_f91e2468 ON public.dominial_imovel USING btree (proprietario_id);


--
-- Name: dominial_imovel_terra_indigena_id_id_38bc4068; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_imovel_terra_indigena_id_id_38bc4068 ON public.dominial_imovel USING btree (terra_indigena_id_id);


--
-- Name: dominial_lancamento_adquirente_id_b4067ce9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_adquirente_id_b4067ce9 ON public.dominial_lancamento USING btree (adquirente_id);


--
-- Name: dominial_lancamento_cartorio_origem_id_d2dbfead; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_cartorio_origem_id_d2dbfead ON public.dominial_lancamento USING btree (cartorio_origem_id);


--
-- Name: dominial_lancamento_cartorio_transacao_id_d90a2ffa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_cartorio_transacao_id_d90a2ffa ON public.dominial_lancamento USING btree (cartorio_transacao_id);


--
-- Name: dominial_lancamento_documento_id_2e607197; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_documento_id_2e607197 ON public.dominial_lancamento USING btree (documento_id);


--
-- Name: dominial_lancamento_documento_origem_id_cb42b164; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_documento_origem_id_cb42b164 ON public.dominial_lancamento USING btree (documento_origem_id);


--
-- Name: dominial_lancamento_tipo_id_5c4464a0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_tipo_id_5c4464a0 ON public.dominial_lancamento USING btree (tipo_id);


--
-- Name: dominial_lancamento_transmitente_id_a3847c12; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamento_transmitente_id_a3847c12 ON public.dominial_lancamento USING btree (transmitente_id);


--
-- Name: dominial_lancamentopessoa_lancamento_id_f9ce28e8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamentopessoa_lancamento_id_f9ce28e8 ON public.dominial_lancamentopessoa USING btree (lancamento_id);


--
-- Name: dominial_lancamentopessoa_pessoa_id_029bf5e2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_lancamentopessoa_pessoa_id_029bf5e2 ON public.dominial_lancamentopessoa USING btree (pessoa_id);


--
-- Name: dominial_origemfimcadeia_lancamento_id_0620e2b7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_origemfimcadeia_lancamento_id_0620e2b7 ON public.dominial_origemfimcadeia USING btree (lancamento_id);


--
-- Name: dominial_pessoas_cpf_698b83d4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_pessoas_cpf_698b83d4_like ON public.dominial_pessoas USING btree (cpf varchar_pattern_ops);


--
-- Name: dominial_terraindigenareferencia_codigo_ac05b0aa_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_terraindigenareferencia_codigo_ac05b0aa_like ON public.dominial_terraindigenareferencia USING btree (codigo varchar_pattern_ops);


--
-- Name: dominial_tis_codigo_17a5975a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_tis_codigo_17a5975a_like ON public.dominial_tis USING btree (codigo varchar_pattern_ops);


--
-- Name: dominial_tis_imovel_imovel_id_6066c688; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_tis_imovel_imovel_id_6066c688 ON public.dominial_tis_imovel USING btree (imovel_id);


--
-- Name: dominial_tis_imovel_tis_codigo_id_ca327d29; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_tis_imovel_tis_codigo_id_ca327d29 ON public.dominial_tis_imovel USING btree (tis_codigo_id);


--
-- Name: dominial_tis_terra_referencia_id_d74be020; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dominial_tis_terra_referencia_id_d74be020 ON public.dominial_tis USING btree (terra_referencia_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_adquirente_id_471a14a6_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_adquirente_id_471a14a6_fk_dominial_ FOREIGN KEY (adquirente_id) REFERENCES public.dominial_pessoas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_averbacao_tipo_id_5df8eda8_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_averbacao_tipo_id_5df8eda8_fk_dominial_ FOREIGN KEY (averbacao_tipo_id) REFERENCES public.dominial_averbacoestipo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_cartorio_id_4225ad19_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_cartorio_id_4225ad19_fk FOREIGN KEY (cartorio_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_cartorio_origem_id_5c17b152_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_cartorio_origem_id_5c17b152_fk FOREIGN KEY (cartorio_origem_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_imovel_id_id_1a0ed79f_fk_dominial_imovel_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_imovel_id_id_1a0ed79f_fk_dominial_imovel_id FOREIGN KEY (imovel_id_id) REFERENCES public.dominial_imovel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_registro_tipo_id_09566af2_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_registro_tipo_id_09566af2_fk_dominial_ FOREIGN KEY (registro_tipo_id) REFERENCES public.dominial_registrotipo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_tipo_alteracao_id_id_0e059b13_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_tipo_alteracao_id_id_0e059b13_fk_dominial_ FOREIGN KEY (tipo_alteracao_id_id) REFERENCES public.dominial_alteracoestipo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_alteracoes dominial_alteracoes_transmitente_id_fd432374_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_alteracoes
    ADD CONSTRAINT dominial_alteracoes_transmitente_id_fd432374_fk_dominial_ FOREIGN KEY (transmitente_id) REFERENCES public.dominial_pessoas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documento dominial_documento_cartorio_id_a2f03235_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_cartorio_id_a2f03235_fk_dominial_ FOREIGN KEY (cartorio_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documento dominial_documento_cri_atual_id_d49d3fd5_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_cri_atual_id_d49d3fd5_fk_dominial_ FOREIGN KEY (cri_atual_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documento dominial_documento_cri_origem_id_b95f93a9_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_cri_origem_id_b95f93a9_fk_dominial_ FOREIGN KEY (cri_origem_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documento dominial_documento_imovel_id_a07f1631_fk_dominial_imovel_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_imovel_id_a07f1631_fk_dominial_imovel_id FOREIGN KEY (imovel_id) REFERENCES public.dominial_imovel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documento dominial_documento_tipo_id_65eb9188_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documento
    ADD CONSTRAINT dominial_documento_tipo_id_65eb9188_fk FOREIGN KEY (tipo_id) REFERENCES public.dominial_documentotipo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documentoimportado dominial_documentoim_documento_id_1dcef329_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documentoimportado
    ADD CONSTRAINT dominial_documentoim_documento_id_1dcef329_fk_dominial_ FOREIGN KEY (documento_id) REFERENCES public.dominial_documento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documentoimportado dominial_documentoim_imovel_origem_id_ee4df2a9_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documentoimportado
    ADD CONSTRAINT dominial_documentoim_imovel_origem_id_ee4df2a9_fk_dominial_ FOREIGN KEY (imovel_origem_id) REFERENCES public.dominial_imovel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_documentoimportado dominial_documentoim_importado_por_id_f35b7a5c_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_documentoimportado
    ADD CONSTRAINT dominial_documentoim_importado_por_id_f35b7a5c_fk_auth_user FOREIGN KEY (importado_por_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_imovel dominial_imovel_cartorio_id_9936b98f_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_imovel
    ADD CONSTRAINT dominial_imovel_cartorio_id_9936b98f_fk FOREIGN KEY (cartorio_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_imovel dominial_imovel_proprietario_id_f91e2468_fk_dominial_pessoas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_imovel
    ADD CONSTRAINT dominial_imovel_proprietario_id_f91e2468_fk_dominial_pessoas_id FOREIGN KEY (proprietario_id) REFERENCES public.dominial_pessoas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_imovel dominial_imovel_terra_indigena_id_id_38bc4068_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_imovel
    ADD CONSTRAINT dominial_imovel_terra_indigena_id_id_38bc4068_fk_dominial_ FOREIGN KEY (terra_indigena_id_id) REFERENCES public.dominial_tis(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_adquirente_id_b4067ce9_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_adquirente_id_b4067ce9_fk_dominial_ FOREIGN KEY (adquirente_id) REFERENCES public.dominial_pessoas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_cartorio_origem_id_d2dbfead_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_cartorio_origem_id_d2dbfead_fk_dominial_ FOREIGN KEY (cartorio_origem_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_cartorio_transacao_i_d90a2ffa_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_cartorio_transacao_i_d90a2ffa_fk_dominial_ FOREIGN KEY (cartorio_transacao_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_cartorio_transmissao_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_cartorio_transmissao_id_fk FOREIGN KEY (cartorio_transmissao_id) REFERENCES public.dominial_cartorios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_documento_id_2e607197_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_documento_id_2e607197_fk_dominial_ FOREIGN KEY (documento_id) REFERENCES public.dominial_documento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_documento_origem_id_cb42b164_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_documento_origem_id_cb42b164_fk_dominial_ FOREIGN KEY (documento_origem_id) REFERENCES public.dominial_documento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_tipo_id_5c4464a0_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_tipo_id_5c4464a0_fk FOREIGN KEY (tipo_id) REFERENCES public.dominial_lancamentotipo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamento dominial_lancamento_transmitente_id_a3847c12_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamento
    ADD CONSTRAINT dominial_lancamento_transmitente_id_a3847c12_fk_dominial_ FOREIGN KEY (transmitente_id) REFERENCES public.dominial_pessoas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamentopessoa dominial_lancamentop_lancamento_id_f9ce28e8_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamentopessoa
    ADD CONSTRAINT dominial_lancamentop_lancamento_id_f9ce28e8_fk_dominial_ FOREIGN KEY (lancamento_id) REFERENCES public.dominial_lancamento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_lancamentopessoa dominial_lancamentop_pessoa_id_029bf5e2_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_lancamentopessoa
    ADD CONSTRAINT dominial_lancamentop_pessoa_id_029bf5e2_fk_dominial_ FOREIGN KEY (pessoa_id) REFERENCES public.dominial_pessoas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_origemfimcadeia dominial_origemfimca_lancamento_id_0620e2b7_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_origemfimcadeia
    ADD CONSTRAINT dominial_origemfimca_lancamento_id_0620e2b7_fk_dominial_ FOREIGN KEY (lancamento_id) REFERENCES public.dominial_lancamento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_tis_imovel dominial_tis_imovel_imovel_id_6066c688_fk_dominial_imovel_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_tis_imovel
    ADD CONSTRAINT dominial_tis_imovel_imovel_id_6066c688_fk_dominial_imovel_id FOREIGN KEY (imovel_id) REFERENCES public.dominial_imovel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_tis_imovel dominial_tis_imovel_tis_codigo_id_ca327d29_fk_dominial_tis_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_tis_imovel
    ADD CONSTRAINT dominial_tis_imovel_tis_codigo_id_ca327d29_fk_dominial_tis_id FOREIGN KEY (tis_codigo_id) REFERENCES public.dominial_tis(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dominial_tis dominial_tis_terra_referencia_id_d74be020_fk_dominial_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dominial_tis
    ADD CONSTRAINT dominial_tis_terra_referencia_id_d74be020_fk_dominial_ FOREIGN KEY (terra_referencia_id) REFERENCES public.dominial_terraindigenareferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict lfMmYSJ8ocw5F0q6xopoJejxA2i0Xt8FKEsbwKGlc4um26gG06SmyAO35v3t6Bc

