# Generated by Django 5.2.3 on 2025-06-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorios',
            options={'ordering': ['estado', 'cidade', 'nome'], 'verbose_name': 'Cartório', 'verbose_name_plural': 'Cartórios'},
        ),
        migrations.AddField(
            model_name='cartorios',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartorios',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='cns',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
