# Generated by Django 5.2.3 on 2025-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0002_alter_cartorios_options_cartorios_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoCartorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('total_cartorios', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Importação de Cartórios',
                'verbose_name_plural': 'Importações de Cartórios',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
