# Generated by Django 5.2.3 on 2025-06-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0003_importacaocartorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('transmissao', 'Transmissão'), ('matricula', 'Matrícula')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='LancamentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('registro', 'Registro'), ('averbacao', 'Averbação')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Lançamento',
                'verbose_name_plural': 'Tipos de Lançamento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('livro', models.CharField(max_length=50)),
                ('folha', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('cartorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dominial.cartorios')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominial.imovel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dominial.documentotipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'unique_together': {('numero', 'cartorio')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor_transacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('adquirente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirente_lancamento', to='dominial.pessoas')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominial.documento')),
                ('transmitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmitente_lancamento', to='dominial.pessoas')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dominial.lancamentotipo')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
            },
        ),
    ]
