# Generated by Django 5.2.3 on 2025-06-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0006_documento_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentotipo',
            options={'verbose_name': 'Tipo de Lançamento', 'verbose_name_plural': 'Tipos de Lançamento'},
        ),
        migrations.AddField(
            model_name='lancamento',
            name='cartorio_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartorio_origem_lancamento', to='dominial.cartorios'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='data_origem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='documento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_origem', to='dominial.documento'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='eh_inicio_matricula',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='folha_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='forma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='livro_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_cartorio_origem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_data_origem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_descricao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_folha_origem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_forma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_livro_origem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_observacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lancamentotipo',
            name='requer_titulo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lancamentotipo',
            name='tipo',
            field=models.CharField(choices=[('averbacao', 'Averbação'), ('registro', 'Registro'), ('encerrar_matricula', 'Encerrar Matrícula'), ('inicio_matricula', 'Início de Matrícula'), ('transcricao', 'Transcrição')], max_length=50),
        ),
    ]
