# Generated by Django 5.2.3 on 2025-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0008_lancamento_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='numero_lancamento',
            field=models.CharField(blank=True, help_text='Número/código do lançamento gerado pelo cartório', max_length=50, null=True),
        ),
    ]
