# Generated by Django 5.2.3 on 2025-06-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0009_lancamento_numero_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('transmitente', 'Transmitente'), ('adquirente', 'Adquirente')], max_length=20)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual da participação (0-100)', max_digits=5)),
                ('nome_digitado', models.CharField(blank=True, help_text='Nome digitado caso pessoa não existisse', max_length=255, null=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='dominial.lancamento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dominial.pessoas')),
            ],
            options={
                'verbose_name': 'Pessoa do Lançamento',
                'verbose_name_plural': 'Pessoas do Lançamento',
                'unique_together': {('lancamento', 'pessoa', 'tipo')},
            },
        ),
    ]
