# Generated by Django 5.2.3 on 2025-06-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0010_lancamentopessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
