# Generated by Django 5.2.3 on 2025-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0012_alter_alteracoes_area_alter_lancamento_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['id'], 'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AddField(
            model_name='tis',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área em hectares', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tis',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
