# Generated by Django 5.2.3 on 2025-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0014_remove_tis_estado_tisestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tis',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
