# Generated by Django 5.2.3 on 2025-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0015_tis_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tis',
            name='estado',
            field=models.CharField(blank=True, help_text='Estados separados por vírgula (ex: AM, PA, MT)', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TIsEstado',
        ),
    ]
