# Generated by Django 5.2.3 on 2025-07-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0016_alter_tis_estado_delete_tisestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='sigef',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='sncr',
        ),
    ]
