# Generated by Django 5.2.3 on 2025-07-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0017_remove_sncr_sigef_descricao_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='cartorio_transacao',
            field=models.ForeignKey(blank=True, help_text='Cartório onde foi registrada a transmissão', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartorio_transacao_lancamento', to='dominial.cartorios'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='cartorio_origem',
            field=models.ForeignKey(blank=True, help_text='Cartório de origem (início de matrícula)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartorio_origem_lancamento', to='dominial.cartorios'),
        ),
    ]
