# Generated by Django 5.2.3 on 2025-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0018_lancamento_cartorio_transacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='data_transacao',
            field=models.DateField(blank=True, help_text='Data da transação', null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='folha_transacao',
            field=models.CharField(blank=True, help_text='Folha da transação', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='livro_transacao',
            field=models.CharField(blank=True, help_text='Livro da transação', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data_origem',
            field=models.DateField(blank=True, help_text='Data da origem', null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='folha_origem',
            field=models.CharField(blank=True, help_text='Folha da origem', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='livro_origem',
            field=models.CharField(blank=True, help_text='Livro da origem', max_length=50, null=True),
        ),
    ]
