# Generated by Django 5.2.3 on 2025-07-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0019_lancamento_data_transacao_lancamento_folha_transacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentopessoa',
            name='percentual',
        ),
    ]
