# Generated by Django 5.2.3 on 2025-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0020_remove_lancamentopessoa_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nivel_manual',
            field=models.IntegerField(blank=True, help_text='Nível manual na árvore da cadeia dominial (0-10)', null=True),
        ),
    ]
