# Generated by Django 5.2.3 on 2025-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0021_documento_nivel_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
