# Generated by Django 5.2.3 on 2025-07-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0023_alter_terraindigenareferencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tis',
            name='etnia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tis',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
