# Generated by Django 5.2.3 on 2025-07-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0025_alter_cartorios_options_cartorios_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cri_atual',
            field=models.ForeignKey(
                blank=True,
                help_text='Cartório de Registro de Imóveis atual do documento',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documentos_cri_atual',
                to='dominial.cartorios',
                verbose_name='CRI Atual'
            ),
        ),
        migrations.AddField(
            model_name='documento',
            name='cri_origem',
            field=models.ForeignKey(
                blank=True,
                help_text='Cartório de Registro de Imóveis da origem (quando criado automaticamente)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documentos_cri_origem',
                to='dominial.cartorios',
                verbose_name='CRI da Origem'
            ),
        ),
    ]
