# Generated by Django 5.2.3 on 2025-07-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0029_sync_cartorio_transmissao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='cartorio_transmissao',
            field=models.ForeignKey(blank=True, help_text='Cartório onde foi registrada a transmissão (novo padrão)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartorio_transmissao_lancamento', to='dominial.cartorios'),
        ),
    ]
