# Generated by Django 5.2.3 on 2025-07-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0030_fix_cartorio_transmissao_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o documento foi importado', verbose_name='Data de Importação')),
                ('documento', models.ForeignKey(help_text='Documento que foi importado', on_delete=django.db.models.deletion.CASCADE, to='dominial.documento', verbose_name='Documento')),
                ('imovel_origem', models.ForeignKey(help_text='Imóvel de onde o documento foi importado', on_delete=django.db.models.deletion.CASCADE, to='dominial.imovel', verbose_name='Imóvel de Origem')),
                ('importado_por', models.ForeignKey(blank=True, help_text='Usuário que fez a importação', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Documento Importado',
                'verbose_name_plural': 'Documentos Importados',
                'db_table': 'dominial_documentoimportado',
                'ordering': ['-data_importacao'],
                'indexes': [models.Index(fields=['documento'], name='dominial_do_documen_1fd8c4_idx'), models.Index(fields=['imovel_origem'], name='dominial_do_imovel__658f12_idx'), models.Index(fields=['data_importacao'], name='dominial_do_data_im_d37bf6_idx'), models.Index(fields=['importado_por'], name='dominial_do_importa_5dd212_idx')],
                'unique_together': {('documento', 'imovel_origem')},
            },
        ),
    ]
