# Generated by Django 5.2.3 on 2025-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0031_documentoimportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='classificacao_fim_cadeia',
            field=models.CharField(blank=True, choices=[('origem_lidima', 'Imóvel com Origem Lídima'), ('sem_origem', 'Imóvel sem Origem'), ('inconclusa', 'Situação Inconclusa')], help_text='Classificação do imóvel quando a cadeia termina', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='especificacao_fim_cadeia',
            field=models.TextField(blank=True, help_text="Especificação quando o tipo é 'Outra'", null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fim_cadeia',
            field=models.BooleanField(default=False, help_text='Indica se este lançamento marca o fim da cadeia dominial'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='observacoes_fim_cadeia',
            field=models.TextField(blank=True, help_text='Observações sobre o fim de cadeia', null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='tipo_fim_cadeia',
            field=models.CharField(blank=True, choices=[('destacamento_publico', 'Destacamento do Patrimônio Público'), ('outra', 'Outra'), ('sem_origem', 'Sem Origem')], help_text='Tipo do fim de cadeia', max_length=50, null=True),
        ),
    ]
