# Generated by Django 5.2.3 on 2025-08-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0032_lancamento_classificacao_fim_cadeia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='observacoes_fim_cadeia',
        ),
    ]
