# Generated by Django 5.2.3 on 2025-08-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0033_remove_lancamento_observacoes_fim_cadeia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='classificacao_fim_cadeia',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='especificacao_fim_cadeia',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='fim_cadeia',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='tipo_fim_cadeia',
        ),
        migrations.CreateModel(
            name='OrigemFimCadeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_origem', models.IntegerField(help_text='Índice da origem no array de origens (0, 1, 2, ...)')),
                ('fim_cadeia', models.BooleanField(default=False, help_text='Indica se esta origem marca o fim da cadeia')),
                ('tipo_fim_cadeia', models.CharField(blank=True, choices=[('destacamento_publico', 'Destacamento do Patrimônio Público'), ('outra', 'Outra'), ('sem_origem', 'Sem Origem')], help_text='Tipo do fim de cadeia para esta origem', max_length=50, null=True)),
                ('especificacao_fim_cadeia', models.TextField(blank=True, help_text="Especificação quando o tipo é 'Outra' para esta origem", null=True)),
                ('classificacao_fim_cadeia', models.CharField(blank=True, choices=[('origem_lidima', 'Imóvel com Origem Lídima'), ('sem_origem', 'Imóvel sem Origem'), ('inconclusa', 'Situação Inconclusa')], help_text='Classificação do imóvel quando a cadeia termina nesta origem', max_length=50, null=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens_fim_cadeia', to='dominial.lancamento')),
            ],
            options={
                'verbose_name': 'Origem Fim de Cadeia',
                'verbose_name_plural': 'Origens Fim de Cadeia',
                'unique_together': {('lancamento', 'indice_origem')},
            },
        ),
    ]
