# Generated by Django 5.2.3 on 2025-09-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0034_remove_lancamento_classificacao_fim_cadeia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='tipo_documento_principal',
            field=models.CharField(choices=[('matricula', 'Matrícula'), ('transcricao', 'Transcrição')], default='matricula', max_length=20, verbose_name='Tipo do Documento Principal'),
        ),
    ]
