# Generated by Django 5.2.3 on 2025-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0035_imovel_tipo_documento_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='classificacao_fim_cadeia',
            field=models.CharField(blank=True, choices=[('origem_lidima', 'Imóvel com Origem Lídima'), ('sem_origem', 'Imóvel sem Origem'), ('inconclusa', 'Situação Inconclusa')], help_text='Classificação específica para documentos de fim de cadeia', max_length=50, null=True, verbose_name='Classificação do Fim de Cadeia'),
        ),
    ]
