# Generated by Django 5.2.3 on 2025-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0036_add_classificacao_fim_cadeia'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='origem_patrimonio_publico',
            field=models.CharField(blank=True, help_text='Origem específica do patrimônio público (ex: INCRA, Estado, etc.)', max_length=200, null=True, verbose_name='Origem do Patrimônio Público'),
        ),
    ]
