# Generated by Django 5.2.3 on 2025-09-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0037_add_origem_patrimonio_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='origem_patrimonio_publico',
        ),
    ]
