# Generated by Django 5.2.3 on 2025-09-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0038_remove_origem_patrimonio_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='sigla_patrimonio_publico',
            field=models.CharField(blank=True, help_text='Sigla específica do patrimônio público (ex: INCRA, Estado, etc.)', max_length=50, null=True, verbose_name='Sigla do Patrimônio Público'),
        ),
    ]
