# Generated by Django 5.2.3 on 2025-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominial', '0039_add_sigla_patrimonio_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
