name = "cadeiadominial-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "replace-me"

[[d1_databases]]
binding = "DB"
database_name = "cadeiadominial-db"
migrations_dir = "drizzle/migrations"
database_id = "REPLACE_WITH_D1_ID"
